NetStock/Areas/Operation/Controllers/OperationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NetStock.Contract;
using NetStock.ActionFilters;
using System.ComponentModel;
using NetStock.BusinessFactory;

namespace NetStock.Areas.Operation.Controllers
{
    [Authorize]
    [SessionFilter]
    [RouteArea("Operation")]
    public class OperationController : Controller
    {
        // GET: Operation/Operation
        public ActionResult Index()
        {
            return View();
        }



        #region Stock Adjustments


        [Route("StockAdjustments")]
        [HttpGet]
        public ActionResult StockAdjustments()
        {
            var lstStockAdjustments = new NetStock.BusinessFactory.StockAdjustmentHeaderBO().GetList();
            return View("StockAdjustmentList", lstStockAdjustments);

        }

        [Route("StockAdjustment")]
        [HttpGet]
        public ActionResult StockAdjustment(string documentNo)
        {

            NetStock.Contract.StockAdjustmentHeader stockadjustment = null;

            if (documentNo == "NEW")
            {
                stockadjustment = new NetStock.Contract.StockAdjustmentHeader();
                stockadjustment.StockAdjustmentDetails = new List<Contract.StockAdjustmentDetail>();
                stockadjustment.DocumentDate = DateTime.Today.Date;
                stockadjustment.CreatedBy = Session["DEFAULTUSER"].ToString();
                stockadjustment.ModifiedBy = Session["DEFAULTUSER"].ToString();
                stockadjustment.Status = Utility.DEFAULTSTATUS;

                //stockledger.StockInDetails = SampleDataForStockInLedgerDetails();
            }
            else
            {
                stockadjustment = new NetStock.BusinessFactory.StockAdjustmentHeaderBO().GetStockInHeader(new Contract.StockAdjustmentHeader { DocumentNo = documentNo });
                stockadjustment.DocumentNo = documentNo;

                if (stockadjustment.StockAdjustmentDetails == null)
                {
                    stockadjustment.StockAdjustmentDetails = new List<Contract.StockAdjustmentDetail>();
                }

            }

            stockadjustment.CustomersList = NetStock.Utility.GetCustomerList(true);
            stockadjustment.ProductList = NetStock.Utility.GetProductList();

            return View("StockAdjustment", stockadjustment);

        }


        [Route("SaveStockAdjustment")]
        [HttpPost]
        public JsonResult SaveStockAdjustment(NetStock.Contract.StockAdjustmentHeader stockheader)
        {
            var message = string.Empty;
            var result = false;
            try
            {
                stockheader.CreatedBy = Session["DEFAULTUSER"].ToString();
                stockheader.ModifiedBy = Session["DEFAULTUSER"].ToString();
                stockheader.CustomerCode = "";
                stockheader.CustomerName = "";

                var lstProducts = stockheader.StockAdjustmentDetails;
                result = new NetStock.BusinessFactory.StockAdjustmentHeaderBO().SaveStockInHeader(stockheader);
                if (result)
                {
                    message = string.Format("Stock-IN saved successfully. Transaction Reference No. {0}  ", stockheader.DocumentNo);
                }
                else
                {
                    message = "Unable to Save STOCK-IN. Please try again!";
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex.Message);
            }

            return Json(new { success = result, Message = message, POData = stockheader });
        }


        [Route("AddStockAdjustmentProduct")]
        [HttpPost]
        public ActionResult AddStockAdjustmentProduct(string barCode, Int16 quantity = 1, string stockType = "ADD")
        {

            NetStock.Contract.StockAdjustmentDetail stockDetail = new Contract.StockAdjustmentDetail();


            //var productData = new NetStock.BusinessFactory.ProductBO().GetSupplierProductByBarCodeOrDescription(supplierCode,barCode,barCode);
            var productData = new NetStock.BusinessFactory.ProductBO().GetProductByBarCodeOrDescription(new NetStock.Contract.Product { ProductCode = barCode, Description = barCode, BarCode = barCode });



            if (productData != null)
            {
                stockDetail.BarCode = productData.BarCode;
                stockDetail.ProductCode = productData.ProductCode;
                stockDetail.ProductDescription = productData.Description;
                stockDetail.BarCode = productData.BarCode;
                stockDetail.Quantity = quantity;
                stockDetail.DocumentNo = "";
                stockDetail.StockType = stockType;

            }


            return Json(new { Message = "Data", StockAdjustmentDetail = stockDetail }, JsonRequestBehavior.AllowGet);
        }

        [Route("AddPurchaseOrderDetails")]
        [HttpPost]
        public ActionResult AddPurchaseOrderDetails(string productCode, string quantity, string pono, string itemCode, string uniPrice, string totalAmt, string productDescription)
        {
            var _quantity = Convert.ToInt32(quantity);
            var itemNo = Convert.ToInt16(itemCode);
            var _unitPrice = Convert.ToDecimal(uniPrice);
            var _totalAmouunt = Convert.ToDecimal(totalAmt);

            PurchaseOrderDetail PurchaseOrderDetail = new PurchaseOrderDetail();
            PurchaseOrderDetail.ProductCode = productCode;
            PurchaseOrderDetail.Quantity = _quantity;
            PurchaseOrderDetail.PONo = pono;
            //PurchaseOrderDetail.ItemNo = itemNo;
            PurchaseOrderDetail.UnitPrice = _unitPrice;
            //PurchaseOrderDetail.TotalAmount = _totalAmouunt;
            PurchaseOrderDetail.ProductDescription = productDescription;


            return Json(new { Message = "Success", PurchaseOrderDetail = PurchaseOrderDetail }, JsonRequestBehavior.AllowGet);
        }


        [Route("DeleteStockAdjustment")]
        [HttpPost]
        public JsonResult DeleteStockAdjustment(string documentNo)
        {
            var result = false;

            string message = string.Empty;
            try
            {
                result = new NetStock.BusinessFactory.StockAdjustmentHeaderBO().DeleteStockInHeader(new NetStock.Contract.StockAdjustmentHeader { DocumentNo = documentNo, ModifiedBy = Session["DEFAULTUSER"].ToString() });

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex.Message);
            }

            return Json(new { result = result, Message = "Stock Entry deleted successfully.", documentNo = documentNo });



        }



        #endregion


        #region StockInquiry



        [Route("StockInquiry")]
        [HttpGet]
        public ActionResult StockInquiry()
        {
            var stockinquiryHd = new NetStock.Contract.StockInquiryHeader();
            stockinquiryHd.ProductList = Utility.GetProductList();
            stockinquiryHd.ProductLocationList = Utility.GetLookupItemList("LOCATION").ToList();
            //stockinquiryHd.ProductCategoryList = Utility.GetLookupItemList("PRODUCTCATEGORY").ToList();
            stockinquiryHd.ProductCategoryList = new NetStock.BusinessFactory.ProductCategoryBO()
                                                    .GetList()
                                                    .Select(x => new SelectListItem
                                                    {
                                                        Value = x.CategoryCode,
                                                        Text = x.Description
                                                    }).ToList();
            stockinquiryHd.SupplierList = Utility.GetCustomerList(true);
            stockinquiryHd.StockInquiryDetails = new List<NetStock.Contract.StockInquiryDetail>();

            var companyCode = Session["CompanyCode"].ToString();
            stockinquiryHd.BranchList = new BranchBO().GetList()
                .Where(x => x.CompanyCode == companyCode)
                .Select(x => new SelectListItem
                {
                    Value = x.BranchID.ToString(),
                    Text = x.BranchName
                }).ToList();

            return View("StockInquiry", stockinquiryHd);
        }

        [Route("StockInquiryResult")]
        [HttpPost]
        public ActionResult StockInquiryResult(NetStock.Contract.StockInquiryHeader stockinquiryHeader)
        {
            var stockinquiryHd = new NetStock.Contract.StockInquiryHeader();

            stockinquiryHd.ProductCode = stockinquiryHeader.ProductCode;
            stockinquiryHd.ProductCategory = stockinquiryHeader.ProductCategory;
            stockinquiryHd.ProductLocation = stockinquiryHeader.ProductLocation;
            stockinquiryHd.BranchID = stockinquiryHeader.BranchID == 0 ? null : stockinquiryHeader.BranchID;

            stockinquiryHd.ProductList = Utility.GetProductList().Select(x => new SelectListItem
            {
                Value = x.Text,
                Text = x.Text
            }).ToList();
            stockinquiryHd.ProductLocationList = Utility.GetLookupItemList("LOCATION");
            stockinquiryHd.ProductCategoryList = Utility.GetLookupItemList("PRODUCTCATEGORY");
            stockinquiryHd.SupplierList = Utility.GetCustomerList(true);
            stockinquiryHd.StockInquiryDetails = new NetStock.BusinessFactory.StockLedgerBO().StockInquiry(stockinquiryHeader.BranchID, stockinquiryHeader.ProductCode, stockinquiryHeader.ProductCategory, stockinquiryHeader.ProductLocation, stockinquiryHeader.SupplierCode);

            var companyCode = Session["CompanyCode"].ToString();
            stockinquiryHd.BranchList = new BranchBO().GetList()
                .Where(x => x.CompanyCode == companyCode)
                .Select(x => new SelectListItem
                {

NetStock/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;


namespace NetStock.Controllers
{
    public class file
    {
        public string url { get; set; }
        public string name { get; set; }
        public string thumbnailUrl { get; set; }
        public string error { get; set; }
        public int size { get; set; }
        public string deleteUrl { get; set; }
        public string deleteType { get; set; }
    }

    public class UploadController : Controller
    {
        // GET: Upload
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Route("UploadFiles")]
        public JsonResult UploadFiles(HttpPostedFileBase[] files)
        {
            var documentNo = Request.Form["hdnDocumentNo"];
            var myFiles = Request.Form["files"];
            try
            {
                var myfiles = new List<file>();
                /*Lopp for multiple files*/
                foreach (HttpPostedFileBase file in files)
                {
                    /*Geting the file name*/
                    string filename = System.IO.Path.GetFileName(file.FileName);
                    string documentsPath = ConfigurationManager.AppSettings["documentsPath"];
                    string folderpath = documentsPath + "\\" + documentNo;

                    var dirInfo = new System.IO.DirectoryInfo(folderpath);
                    if (!dirInfo.Exists)
                    {
                        dirInfo.Create();
                    }

                    /*Saving the file in server folder*/
                    string filepathtosave = folderpath + "/" + filename;

                    var fileObj = new file();
                    fileObj.name = filename;
                    fileObj.url = "http://" + System.Web.HttpContext.Current.Request.Url.Host + ":" + System.Web.HttpContext.Current.Request.Url.Port + "/UploadImages/" + documentNo + "/" + filename;
                    fileObj.thumbnailUrl = "http://" + System.Web.HttpContext.Current.Request.Url.Host + ":" + System.Web.HttpContext.Current.Request.Url.Port + "/UploadImages/" + documentNo + "/" + filename;
                    fileObj.size = file.ContentLength;
                    fileObj.deleteUrl = "http://" + System.Web.HttpContext.Current.Request.Url.Host + ":" + System.Web.HttpContext.Current.Request.Url.Port + "/UploadImages/" + documentNo + "/" + filename;
                    fileObj.deleteType = "DELETE";
                    //public string deleteUrl { get; set; }
                    //public string deleteType { get; set; }
                    try
                    {
                        file.SaveAs(Server.MapPath("~/UploadImages/" + documentNo + "/" + filename));
                    }
                    catch (Exception ex)
                    {
                        fileObj.error = ex.Message;

                    }
                    myfiles.Add(fileObj);
                    /*HERE WILL BE YOUR CODE TO SAVE THE FILE DETAIL IN DATA BASE*/
                }

                return Json(new { files = myfiles });
            }
            catch
            {
                return Json(false);
            }

            // return Json("Success");
        }


        [HttpGet]
        [Route("UploadFiles")]
        public JsonResult UploadFiles()
        {
            return Json("", JsonRequestBehavior.AllowGet);
        }
    }
}

NetStock/Areas/Operation/Views/Operation/AddStockItem.cshtml
@model NetStock.Contract.StockInDetail



<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="lblHeader">Add/Edit Stock Item </h4>

</div>

@using (Html.BeginForm())
{


    <div class="modal-body form-horizontal" id="modalbody">

        <div class="form-group">
            <div>
                @Html.LabelFor(m => m.ProductCode, new { @class = "control-label input-sm col-md-3" })
                <div class="col-md-4">

                    @Html.DropDownListFor(m => m.ProductCode, Model.ProductsList,"Select Product",  new { @class = "form-control input-sm" })

                </div>
            </div>
        </div>
        <div class="form-group">
            <div>
                @Html.LabelFor(m => m.Quantity, new { @class = "col-md-3 control-label input-sm" })
                <div class="col-md-2">
                    @Html.TextBoxFor(m => m.Quantity, new { @class = "form-control input-sm "  })

                </div>
            </div>
        </div>
        

    </div>

    <div class="modal-footer" id="closemodal">
        <button class="btn" data-dismiss="modal">Cancel</button>
        @*<input class="btn btn-primary" type="submit" value="Save" onclick="Save()" />*@
        <input class="btn btn-primary" type="button" onclick="AddDataToTable()" value="Save" />
    </div>

}

<script type="text/javascript">

    $(function () {
        $(".NumberAutonumeric").autoNumeric('init');
    })
</script>

NetStock/Areas/Operation/Views/Operation/ImageUploads.cshtml
@model List<NetStock.Areas.Operation.Controllers.file>
@section css{
<link href="@Url.Content("~/Content/fileupload/style.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/fileupload/jquery.fileupload.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/fileupload/jquery.fileupload-ui.css")" rel="stylesheet" />
}
@{
    var documentNo = "";

    if (!string.IsNullOrWhiteSpace(Request.QueryString["documentno"]))
    {
        documentNo = Request.QueryString["documentno"];
    }
}

<div class="box box-solid box-default">

    <!-- Header Title -->
    <div class="box-header with-border">
        <h3 class="box-title">Uploaded Images</h3>
    </div>
    <div class="box-body">
        <fieldset class="form-horizontal">
            <div class="form-group row">
                <div class="col-md-12">
                    <form id="fileupload" name="fileupload" method="POST" action="@Url.Action("UploadFiles", "Upload")" enctype="multipart/form-data">
                        <!-- Redirect browsers with JavaScript disabled to the origin page -->
                        <noscript>
                            <input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/">
                        </noscript>
                        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
                        <div class="row fileupload-buttonbar">
                            <div class="col-lg-7">
                                <!-- The fileinput-button span is used to style the file input field as button -->
                                <span class="btn btn-success fileinput-button btn-sm">
                                    <i class="glyphicon glyphicon-plus"></i>
                                    <span>Add files...</span>
                                    <input type="file" name="files" multiple>
                                </span>
                                <button type="submit" class="btn btn-primary btn-sm start" id="btnStartUpload">
                                    <i class="glyphicon glyphicon-upload"></i>
                                    <span>Start upload</span>
                                </button>
                                <button type="reset" class="btn btn-warning btn-sm cancel">
                                    <i class="glyphicon glyphicon-ban-circle"></i>
                                    <span>Cancel upload</span>
                                </button>
                                <button type="button" class="btn btn-danger btn-sm delete">
                                    <i class="glyphicon glyphicon-trash"></i>
                                    <span>Delete</span>
                                </button>
                                @*<input type="checkbox" class="toggle">*@
                                <!-- The global file processing state -->
                                <span class="fileupload-process"></span>
                            </div>
                            <!-- The global progress state -->
                            <div class="col-lg-5 fileupload-progress fade">
                                <!-- The global progress bar -->
                                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                                    <div class="progress-bar progress-bar-success" style="width: 0%;"></div>
                                </div>
                                <!-- The extended global progress state -->
                                <div class="progress-extended">&nbsp;</div>
                            </div>
                        </div>
                        <!-- The table listing the files available for upload/download -->
                        <div class="row">
                            <div class="col-md-12">
                                <table role="presentation" class="table table-striped">
                                    <tbody class="files">
                                        @if (Model != null)
                                        {
                                            for (var i = 0; i < Model.Count; i++)
                                            {
                                                <tr class="template-upload fade in">
                                                    <td>
                                                        <span class="preview"><img src="@Url.Content(Model[i].url)" width="80" height="47" /></span>
                                                    </td>
                                                    <td>
                                                        <p class="name">@Model[i].name</p>
                                                        <strong class="error text-danger"></strong>
                                                    </td>
                                                    <td>
                                                        <p class="size">59.08 KB</p>
                                                        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
                                                    </td>
                                                    <td>
                                                        <div>
                                                            @*<button class="btn btn-primary start" disabled="disabled">
                                                                    <i class="glyphicon glyphicon-upload"></i>
                                                                    <span>Start</span>
                                                                </button>*@

                                                            <button type="button" class="btn btn-danger cancel" data-src="@Url.Content(Model[i].url)" data-name="@Model[i].name" id="btnDelete_@i" onclick="btnDelete(@i);">
                                                                <i class="glyphicon glyphicon-trash"></i>
                                                                <span>Delete</span>
                                                            </button>
                                                            </div>
                                                    </td>
                                                </tr>
                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-11"></div>
                            <div class="col-md-1">
                                <button type="button" class="btn btn-primary btn-sm" onclick="fnBack();"><i class="fa fa-undo" aria-hidden="true"></i>&nbsp;Back</button>
                            </div>
                        </div>

                        <input type="hidden" name="hdnDocumentNo" id="hdnDocumentNo" value="@documentNo" />
                        <input type="hidden" name="hdnFileName" id="hdnFileName" />
                    </form>
                </div>

            </div>
        </fieldset>
    </div>
</div>
@section Scripts {
<!-- File Upload Scripts -->
<script src="@Url.Content("~/Scripts/jquery.ui.widget.js")"></script>
<script src="//blueimp.github.io/JavaScript-Templates/js/tmpl.min.js"></script>
<script src="//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>
<script src="@Url.Content("~/Scripts/fileupload/jquery.iframe-transport.js")"></script>
<script src="@Url.Content("~/Scripts/fileupload/jquery.fileupload.js")"></script>
<script src="@Url.Content("~/Scripts/fileupload/jquery.fileupload-process.js")"></script>
<script src="@Url.Content("~/Scripts/fileupload/jquery.fileupload-image.js")"></script>
<script src="@Url.Content("~/Scripts/fileupload/jquery.fileupload-validate.js")"></script>
<script src="@Url.Content("~/Scripts/fileupload/jquery.fileupload-ui.js")"></script>
<script src="@Url.Content("~/Scripts/fileupload/main.js")"></script>
<script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
            <button class="btn btn-primary start" disabled style="display:none;">
                <i class="glyphicon glyphicon-upload"></i>
                <span>Start</span>
            </button>
            {% } %}
            {% if (!i) { %}
            <button class="btn btn-warning cancel">
                <i class="glyphicon glyphicon-ban-circle"></i>
                <span>Cancel</span>
            </button>
            {% } %}
        </td>
    </tr>
    {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img height="100" widht="100" src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
            <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
            @*<button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}" {% if (file.deletewithcredentials) { %} data-xhr-fields='{"withCredentials":true}' {% } %}>
                <i class="glyphicon glyphicon-trash"></i>
                <span>Delete</span>
            </button>*@
            @*<input type="checkbox" name="delete" value="1" class="toggle">*@
            {% } else { %}
            <button class="btn btn-warning cancel">
                <i class="glyphicon glyphicon-ban-circle"></i>
                <span>Cancel</span>
            </button>
            {% } %}
        </td>
    </tr>
    {% } %}
</script>
<script type="text/javascript">
    var uploadUrl = '@Url.Content("~/Operation/UploadFiles?documentno=")' + '@documentNo'

    function btnDelete(index){
        var fileName = $('#btnDelete_' + index).data('name');
        //var r = confirm('Are you sure do you want to delete file \'' + fileName + '\' ?');
        //if (r) {
            $('#hdnFileName').val(fileName);

            $('#fileupload').attr({
                'action': '@Url.Content("~/Operation/DeleteFile")'
            }).removeAttr('enctype');

            $('#fileupload').submit();
        //}
    }

    function fnBack() {
        var documentType = ('@Request.QueryString["documentType"]' == '@DocumentType.DOMESTIC.ToString()' ? "GoodsReceiveDomestic" : "GoodsReceiveOverseas");
        if (documentType == 'GoodsReceiveDomestic')
            location.href = '@Url.Content("~/Operation/GoodsReceiveDomestic")' + '?documentNo=' + '@documentNo' + '&branchID=' + '@HttpContext.Current.Session["BranchId"].ToString()';
        else if (documentType == 'GoodsReceiveOverseas')
            location.href = '@Url.Content("~/Operation/GoodsReceiveOverseas")' + '?documentNo=' + '@documentNo' + '&branchID=' + '@HttpContext.Current.Session["BranchId"].ToString()';
    }
</script>
}

NetStock/Areas/Operation/Views/Operation/OrderItem.cshtml
@model NetStock.Contract.OrderDetail

@using (Html.BeginForm())
{
    
        <div class="form-group">
            <div>
                @Html.LabelFor(m => m.Quantity, new { @class = "col-md-3 control-label input-sm" })
                <div class="col-md-4">
                    @Html.TextBoxFor(m => m.Quantity, new { @class = "form-control input-sm " })

                </div>
            </div>
        </div>
        <div class="form-group">
            <div>
                @Html.LabelFor(m => m.ProductCode, new { @class = "control-label input-sm col-md-3" })
                <div class="col-md-2">
                    @Html.TextBoxFor(m => m.BarCode, new { @class = "form-control input-sm " })
                </div>
            </div>
        </div>
        <div class="form-group">

            <div>
                <div class="col-md-4">
                    @Html.HiddenFor(m => m.OrderNo)
                    @Html.HiddenFor(m => m.BarCode)
                    @Html.HiddenFor(m => m.ItemNo)

                </div>
            </div>

        </div>


}

NetStock/Areas/Operation/Views/Operation/ProductPhoto.cshtml
@model NetStock.Contract.ProductImage
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="lblHeader">Product Photo</h4>
</div>



<div class="modal-body form-horizontal">
    <div class="form-group">
        <div>
            @Html.LabelFor(m => m.Code, new { @class = "control-label input-sm col-md-2" })
            <div class="col-md-4">

                @Html.DisplayFor(m => m.Code, new { @class = "form-control input-sm" })


            </div>
        </div>
    </div>
    <div class="form-group">
        <div>
            @Html.LabelFor(m => m.ProductImg, new { @class = "col-md-2 control-label input-sm" })
            <div class="col-md-8">
                @{
                    if (Model != null)
                    {
                        if (Model.ProductImg != null)
                        {
                            <img id="target" style="width:150px;height:150px" src="data:image/jpeg;base64,@System.Convert.ToBase64String(Model.ProductImg)" />
                        }
                    }
                }

            </div>
        </div>
    </div>
</div>

<div class="modal-footer" id="closemodal">
    <button class="btn" data-dismiss="modal">OK</button>
</div>